{
  var secondsBetweenAnims = 2;

  // This script looks at a precomp's markers and creates keyframes for each animation using time remapping
  // If any existing timeremapping exists, it will try and fill in the missing keyframes (i.e. isFresh=false)

  function createKeyframes(layer, markers) {
    var timeRemap = layer.property("ADBE Time Remapping");

    // Turn on time remapping if it's not already enabled
    if (layer.timeRemapEnabled === false) {
      layer.timeRemapEnabled = true;

      // Two keyframes are always generated by turning on time remapping, remove last one
      timeRemap.removeKey(2);
    }

    var isFresh = timeRemap.numKeys === 1;
    var markerIndx = 1 + (isFresh ? 0 : timeRemap.numKeys);
    var lastEnd = isFresh
      ? layer.inPoint
      : timeRemap.keyTime(timeRemap.numKeys);

    // Create keyframes for each pair of markers
    for (var i = markerIndx; i <= markers.numKeys; i += 2) {
      var markerStart = markers.keyTime(i); // The time of the marker that signals the start of the animation
      var markerEnd = markers.keyTime(i + 1); // The time of the marker that signals the end of the animation

      var duration = markerEnd - markerStart; // The duration of the animation
      lastEnd += secondsBetweenAnims;

      timeRemap.setValueAtTime(lastEnd, markerStart);
      timeRemap.setValueAtTime(lastEnd + duration, markerEnd);

      lastEnd += duration;
    }

    if (isFresh) timeRemap.removeKey(1); // Remove the first keyframe as it's unnecessary

    // For readability, set the interpolation type to hold on the animation end markers
    for (var i = 1; i <= markers.numKeys; i += 1) {
      timeRemap.setInterpolationTypeAtKey(
        i,
        KeyframeInterpolationType.LINEAR,
        i % 2 === 0
          ? KeyframeInterpolationType.HOLD
          : KeyframeInterpolationType.LINEAR
      );
    }
  }

  // Main function
  function main() {

    var activeItem = app.project.activeItem;
    if (! activeItem instanceof CompItem) {
      alert("No opened composition.");
      return;
    }

    app.beginUndoGroup("Adjust Precomp Timings");

    // Create keyframes for each selected layer
    for (var i = 0; i < activeItem.selectedLayers.length; i++) {
      var selectedLayer = activeItem.selectedLayers[i];
      var precomp = selectedLayer.source;
      if (!(precomp instanceof CompItem)) continue;

      var markers = precomp.markerProperty;
      if (markers.numKeys < 2 || markers.numKeys % 2 !== 0) {
        alert(
          "The precomp must have at least two markers and an even number of markers."
        );
        return;
      }

      createKeyframes(selectedLayer, precomp.markerProperty);
    }

    app.endUndoGroup();
  }

  main();
}
